### ISSUE TITLE
Testing: GCC 13.1.0

### ISSUE THREAD

**Issue by mathomp4** [GEOS-ESM/ESMA-Baselibs#106]
Using this a tracker for issues with GCC 13.1.0

**Comment by mathomp4** [comment]
# GCC 13.1.0 on M1 Mac

## Compiling GCC

### Official Tarball

I grabbed the official tarball from GCC and tried to build but:

```
*** Configuration aarch64-apple-darwin22.4.0 not supported
```

Interestingly, this failed in the *make* step and not the *configure* step. Hmm. 

Nothing is showing up yet on the [buildstat page](https://gcc.gnu.org/gcc-13/buildstat.html), so I might just be too early. 

I wonder if it's the usual Apple Clang issue that spack protects against:
```python
    # https://github.com/iains/gcc-12-branch/issues/6
    conflicts("%apple-clang@14:14.0")
```

### Iain Repo

Next thought was the as with GCC 12.2 on M1, we move to the @iains repos.

I see there is a [`gcc-13-branch` repo](https://github.com/iains/gcc-13-branch) now but it's still on rc3. For now, I'll wait and monitor.

### Build GCC 13 with GCC 12

So if Apple Clang is the issue, we can try a bootstrap from a working GCC to a new GCC.

**Comment by iains** [comment]
The gcc-13-1-darwin-r0 branch should be ready this week - it takes time to test across the whole range of versions and GCC-13-1 was only release this morning :)

**Comment by mathomp4** [comment]
> The gcc-13-1-darwin-r0 branch should be ready this week - it takes time to test across the whole range of versions and GCC-13-1 was only release this morning :)
> 
> edit: we are hoping to be able to find time to upstream some of the work for GCC14.

@iains I figured I was jumping the gun. I guess part of me just hoped all the fixes were in GCC 13 after I saw:

> Support for new CPU features in the ARM, x86 family, RISC-V and LoongArch

and said, hey, M1 is Arm! 😄 

If we can ever just get clang to build GCC inside of spack, I suppose that would solve some problems (though not [this crazy issue](https://github.com/spack/spack/issues/34953) which I still cannot figure out...)
