### ISSUE TITLE
Add FRE-NCtools to Baselibs

### ISSUE THREAD

**Issue by mathomp4** [GEOS-ESM/ESMA-Baselibs#4]
Per @sanAkel:

> Good Morning, Matt, Tom,
> 
> Matt, would you please help me get following built with your latest g5_modules/Baselibs.
> https://github.com/NOAA-GFDL/FRE-NCtools
> This is our first step to follow up from yesterdays' meetings. 
> 
> Good news is that they (GFDL) will maintain our (GEOS) specific customizations (cMake, plug/interface, etc) in MOM6 branches. In next couple of weeks we'll hash out these details so that way our code will join the `main stream' and become part of their master!
> 
> Thanks a lot for all the help!
> Santha

**Comment by sanAkel** [comment]
@mathomp4 are you sure you want to add it to baselibs? Its okay with me if that's what you guys want to. 

I'm leaving this comment because my request was only to build using existing baselibs. 

In any case, I'll happily take whatever works and you all think is best!

**Comment by mathomp4** [comment]
@sanAkel Ohh. I thought you wanted it in Baselibs because MOM6 would need it during its build.

Is it only a post/pre-processing utility?

**Comment by sanAkel** [comment]
yes! It is. And should be treated as "external" to MOM-6

**Comment by mathomp4** [comment]
> yes! It is. And should be treated as "external" to MOM-6

That's a lot easier. One last question: do you need the MPI version? It looks like the `configure` command had an option for MPI, but I don't exactly know what that does.

**Comment by sanAkel** [comment]
Serial (non-MPI) version would be fine, may be easier to work with! 

We can think of MPI later...

**Comment by mathomp4** [comment]
@sanAkel Well, I tried it with `--with-mpi=yes` because why not. So there are two modules available now on SLES11 and SLES12 in the SI Team space:
```
other/FRE-NCtools/2020Mar16
```

Now, a few things. First, I built the current `master` of the Git repo because it had a semi-sane `configure` setup. The last release they made had some weird make system I didn't want to deal with.

Second, I have no idea how to test it  My guess is you'll run into all sorts of issue unless you've sourced a `g5_modules` but maybe try it without for now. (I think it will need some `LD_LIBRARY_PATH` eventually.)

On SLES 11, I built the module with:
```
other/comp/gcc-6.3
comp/intel-18.0.5.274
mpi/impi-18.0.5.274
```
and you'l need to have those loaded first. (They are the modules from the current GEOSgcm on SLES11.)

On SLES12, it used:
```
comp/gcc/6.5.0
comp/intel/18.0.5.274
mpi/impi/19.1.0.166
```
To make life "easier", I have the Lua mod `load()` them so it's "automatic". Or it'll cause all sorts of issues and I can make them `prereq()`.

**Comment by sanAkel** [comment]
Sweet!! Many thanks! I'll try it...

**Comment by sanAkel** [comment]
I'm sure you have C48 test case somewhere. Could you please point me to it. 

I only need (C48) grid info. Just want to get a super coarse grid: C48 atmosphere and 2-deg (or 5-deg) ocean. This util is for the latter. I'll pass the coarse ocean grids to Atanas/Yury once I have them.

**Comment by mathomp4** [comment]
C48? So high-res! C12 is "regular resolution" (For possible nightly testing, we'd love a very-low-res coupled case!)

What do you need? Restarts? Boundary conditions? Here's an example experiment at C48:
/discover/nobackup/mathomp4/Experiments/stock-gcm-2020Mar10-1day-c48

I can provide a C12 or C24 as well if wanted

**Comment by sanAkel** [comment]
Thanks!! 


Point me C12 please! 

We share same goal(s)!

**Comment by mathomp4** [comment]
Here is the C12/Reynolds tile file we currently use: 
```
/gpfsm/dnb02/ltakacs/bcs/Icarus/LAND/CF0012x6C/CF0012x6C_DE0360xPE0180-Pfafstetter.til
```
