### ISSUE TITLE
Update to netCDF-C 4.9.2, netCDF-Fortran 4.6.1

### ISSUE THREAD

**Issue by mathomp4** [GEOS-ESM/ESMA-Baselibs#92]
netCDF-C 4.9.2 was just released:

https://github.com/Unidata/netcdf-c/releases/tag/v4.9.2

ETA: netCDF-Fortran 4.6.1 was also released:

https://github.com/Unidata/netcdf-fortran/releases/tag/v4.6.1

I might need to invoke the name of @WardF or @edwardharnett to know if I should/can update to this now, or wait for an update to netCDF-Fortran as I often update both in tandem.

**Comment by WardF** [comment]
I am working on the next netcdf fortran release at the moment; hopefully you should be able to update both in short order :)

**Comment by mathomp4** [comment]
> I am working on the next netcdf fortran release at the moment; hopefully you should be able to update both in short order :)

Woo! Thanks. I'll hold off then. No big need on our end to update as I can't think of any issues with 4.9.0/4.6.0 yet. (And nothing in our code uses netcdf-cxx4 so...who knows! But as long as it keeps building, I'll keep building it! 😄 )
